name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - run: make checkstyle
      - run: ./gradlew lint
      - run: make test
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: app-reports
          path: app/build/reports
          retention-days: 5
